### ISSUE TITLE
Version 2.0.0: Error "Resolving ‘magit-insert-files-1’ template failed -- Cannot find definition"

### ISSUE THREAD

**Issue by dunmaksim** [gekoke/magit-file-icons#8]
Hello!

Today me update `magit-file-icons` to version `2.0.0`, and now I see this message on minibuffer and \*Warnings* buffer:

```text
Error (use-package): magit-file-icons/:config: Resolving ‘magit-insert-files-1’ template failed -- Cannot find definition
```

My settings:

```lisp
(use-package magit-file-icons
  :ensure t
  :after magit
  :config
  (magit-file-icons-mode 1))
```

Emacs 29.3

**Comment by gekoke** [comment]
Hi!

`v2.0.0` is a major version bump in order to accommodate breaking changes to Magit's internals (see #7). If you're not using a very recent version of Magit, this error is expected.

Your options include:
1) updating `magit` to at least MELPA version `magit-20240624`
2) using `magit-file-icons` at `v1.x.x`

`magit-file-icons` relies on the internal structure of the `magit` package looking a certain way, so it will break if any of that ever changes (which will, hopefully, be infrequently)

Let me know if this helps.

**Comment by dunmaksim** [comment]
Yes, that works. Thank you!

**Comment by bcardoso** [comment]
Hello.

After a recent update, I'm getting the same warning about `magit-insert-files-1` with the latest magit (output of `magit-version`: "Magit 5ac6b4f, Transient 0.8.3, Git 2.48.1, Emacs 29.4, gnu/linux") and `magit-file-icons' 2.0.0.

`Error (use-package): magit-file-icons/:config: Resolving ‘magit-insert-files-1’ template failed -- Cannot find definition`
